export const SET_PAYMENT_VISIBILITY_FILTER = 'payment/SET_PAYMENT_VISIBILITY_FILTER';

export const PAYMENT_REQUEST = 'payment/PAYMENT_REQUEST';
export const PAYMENT_FAILURE = 'payment/PAYMENT_FAILURE';
export const PAYMENT_RECEIVE = 'payment/PAYMENT_RECEIVE';

export const WITHDRAWAL_FUNDS_REQUEST = 'payment/WITHDRAWAL_FUNDS_REQUEST';
export const WITHDRAWAL_FUNDS_FAILURE = 'payment/WITHDRAWAL_FUNDS_FAILURE';
export const WITHDRAWAL_FUNDS_RECEIVE = 'payment/WITHDRAWAL_FUNDS_RECEIVE';

export const TRANSACTION_HISTORY_REQUEST = 'payment/TRANSACTION_HISTORY_REQUEST';
export const TRANSACTION_HISTORY_FAILURE = 'payment/TRANSACTION_HISTORY_FAILURE';
export const TRANSACTION_HISTORY_RECEIVE = 'payment/TRANSACTION_HISTORY_RECEIVE';
