export const NAME = 'payment';

export const PaymentFilters = {
  SHOW_ADD_DEPOSIT: 'SHOW_ADD_DEPOSIT',
  SHOW_CASH_OUT: 'SHOW_CASH_OUT',
  SHOW_HISTORY: 'SHOW_HISTORY'
};

export const WITHDRAWAL_STATUS_NEW = 'NEW';
export const WITHDRAWAL_STATUS_CANCELED = 'CANCELED';
export const WITHDRAWAL_STATUS_FINISHED = 'FINISHED';
