export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';

export const LOGOUT = 'auth/LOGOUT';

export const REGISTRATION_REQUEST = 'auth/REGISTRATION_REQUEST';
export const REGISTRATION_FAILURE = 'auth/REGISTRATION_FAILURE';
export const REGISTRATION_SUCCESS = 'auth/REGISTRATION_SUCCESS';

export const FETCH_USER_REQUEST = 'auth/FETCH_USER_REQUEST';
export const FETCH_USER_FAILURE = 'auth/FETCH_USER_FAILURE';
export const FETCH_USER_RECEIVE = 'auth/FETCH_USER_RECEIVE';

export const CLIENT_IP_REQUEST = 'auth/CLIENT_IP_REQUEST';
export const CLIENT_IP_FAILURE = 'auth/CLIENT_IP_FAILURE';
export const CLIENT_IP_RECEIVE = 'auth/CLIENT_IP_RECEIVE';

export const UPDATE_LOGIN_FORM_INFO = 'auth/UPDATE_LOGIN_FORM_INFO';

export const RESTORE_PASSWORD_EMAIL_REQUEST = 'auth/RESTORE_PASSWORD_EMAIL_REQUEST';
export const RESTORE_PASSWORD_EMAIL_FAILURE = 'auth/RESTORE_PASSWORD_EMAIL_FAILURE';
export const RESTORE_PASSWORD_EMAIL_RECEIVE = 'auth/RESTORE_PASSWORD_EMAIL_RECEIVE';

export const RESTORE_PASSWORD_CHECK_KEY_REQUEST = 'auth/RESTORE_PASSWORD_CHECK_KEY_REQUEST';
export const RESTORE_PASSWORD_CHECK_KEY_FAILURE = 'auth/RESTORE_PASSWORD_CHECK_KEY_FAILURE';
export const RESTORE_PASSWORD_CHECK_KEY_RECEIVE = 'auth/RESTORE_PASSWORD_CHECK_KEY_RECEIVE';

export const CLEAR_RESTORE_PASSWORD_DATA = 'auth/CLEAR_RESTORE_PASSWORD_DATA';

export const USER_UPDATE_REQUEST = 'auth/USER_UPDATE_REQUEST';
export const USER_UPDATE_FAILURE = 'auth/USER_UPDATE_FAILURE';
export const USER_UPDATE_RECEIVE = 'auth/USER_UPDATE_RECEIVE';

export const USER_TEMPLATES_REQUEST = 'auth/USER_TEMPLATES_REQUEST';
export const USER_TEMPLATES_FAILURE = 'auth/USER_TEMPLATES_FAILURE';
export const USER_TEMPLATES_RECEIVE = 'auth/USER_TEMPLATES_RECEIVE';

export const TEMPLATE_DELETE_REQUEST = 'auth/TEMPLATE_DELETE_REQUEST';
export const TEMPLATE_DELETE_FAILURE = 'auth/TEMPLATE_DELETE_FAILURE';
export const TEMPLATE_DELETE_RECEIVE = 'auth/TEMPLATE_DELETE_RECEIVE';

export const TEMPLATE_ADD_REQUEST = 'auth/TEMPLATE_ADD_REQUEST';
export const TEMPLATE_ADD_FAILURE = 'auth/TEMPLATE_ADD_FAILURE';
export const TEMPLATE_ADD_RECEIVE = 'auth/TEMPLATE_ADD_RECEIVE';

export const SET_PROFILE_VISIBILITY_FILTER = 'auth/SET_PROFILE_VISIBILITY_FILTER';
