export const NAME = 'auth';

export const ProfileFilters = {
  SHOW_USER_SETTING: 'SHOW_USER_SETTING',
  SHOW_CHANGE_PASSWORD: 'SHOW_CHANGE_PASSWORD',
  SHOW_NOTIFICATIONS: 'SHOW_NOTIFICATIONS',
  SHOW_LANGUAGE: 'SHOW_LANGUAGE'
};
