export const REQUEST_TOURNAMENTS = 'tournaments/REQUEST_TOURNAMENTS';
export const REQUEST_TOURNAMENTS_FAILURE = 'tournaments/REQUEST_TOURNAMENTS_FAILURE';
export const REQUEST_TOURNAMENTS_RECEIVE = 'tournaments/REQUEST_TOURNAMENTS_RECEIVE';
