export const REQUEST_PLAYERS = 'players/REQUEST_PLAYERS';
export const REQUEST_PLAYERS_FAILURE = 'players/REQUEST_PLAYERS_FAILURE';
export const RECEIVE_PLAYERS = 'players/RECEIVE_PLAYERS';

export const REQUEST_PLAYERS_BY_TEAMS = 'players/REQUEST_PLAYERS_BY_TEAMS';
export const REQUEST_PLAYERS_BY_TEAMS_FAILURE = 'players/REQUEST_PLAYERS_BY_TEAMS_FAILURE';
export const RECEIVE_PLAYERS_BY_TEAMS = 'players/RECEIVE_PLAYERS_BY_TEAMS';

export const REQUEST_PLAYERS_STATS = 'players/REQUEST_PLAYERS_STATS';
export const REQUEST_PLAYERS_STATS_FAILURE = 'players/REQUEST_PLAYERS_STATS_FAILURE';
export const RECEIVE_PLAYERS_STATS = 'players/RECEIVE_PLAYERS_STATS';
