export const FETCH_REQUEST = 'room/FETCH_REQUEST';
export const FETCH_REQUEST_FAILURE = 'room/FETCH_REQUEST_FAILURE';
export const FETCH_REQUEST_RECEIVE = 'room/FETCH_REQUEST_RECEIVE';

export const ROOM_BIDS_REQUEST = 'room/ROOM_BIDS_REQUEST';
export const ROOM_BIDS_FAILURE = 'room/ROOM_BIDS_FAILURE';
export const ROOM_BIDS_RECEIVE = 'room/ROOM_BIDS_RECEIVE';

export const ROOM_USERBIDS_REQUEST = 'room/ROOM_USERBIDS_REQUEST';
export const ROOM_USERBIDS_FAILURE = 'room/ROOM_USERBIDS_FAILURE';
export const ROOM_USERBIDS_RECEIVE = 'room/ROOM_USERBIDS_RECEIVE';

export const CLEAR_ROOM_USERBIDS = 'room/CLEAR_ROOM_USERBIDS';

export const STATS_BY_MATCHES_REQUEST = 'room/STATS_BY_MATCHES_REQUEST';
export const STATS_BY_MATCHES_FAILURE = 'room/STATS_BY_MATCHES_FAILURE';
export const STATS_BY_MATCHES_RECEIVE = 'room/STATS_BY_MATCHES_RECEIVE';

export const BID_DELETE_REQUEST = 'room/BID_DELETE_REQUEST';
export const BID_DELETE_FAILURE = 'room/BID_DELETE_FAILURE';
export const BID_DELETE_RECEIVE = 'room/BID_DELETE_RECEIVE';

export const BID_REQUEST = 'room/BID_REQUEST';
export const BID_FAILURE = 'room/BID_FAILURE';
export const BID_RECEIVE = 'room/BID_RECEIVE';

export const BID_UPDATE_REQUEST = 'room/BID_UPDATE_REQUEST';
export const BID_UPDATE_FAILURE = 'room/BID_UPDATE_FAILURE';
export const BID_UPDATE_RECEIVE = 'room/BID_UPDATE_RECEIVE';

export const GET_BID_REQUEST = 'room/GET_BID_REQUEST';
export const GET_BID_FAILURE = 'room/GET_BID_FAILURE';
export const GET_BID_RECEIVE = 'room/GET_BID_RECEIVE';

export const ROOM_FILTER_BIDS = 'room/ROOM_FILTER_BIDS';
// export const CLEAR_CHOOSE_TEAM_FILTER = 'CLEAR_CHOOSE_TEAM_FILTER';
