export const GAMES_FUTURE_REQUEST = 'mygames/GAMES_FUTURE_REQUEST';
export const GAMES_FUTURE_FAILURE = 'mygames/GAMES_FUTURE_FAILURE';
export const GAMES_FUTURE_RECEIVE = 'mygames/GAMES_FUTURE_RECEIVE';

export const GAMES_PAST_REQUEST = 'mygames/GAMES_PAST_REQUEST';
export const GAMES_PAST_FAILURE = 'mygames/GAMES_PAST_FAILURE';
export const GAMES_PAST_RECEIVE = 'mygames/GAMES_PAST_RECEIVE';

export const GAMES_LIVE_REQUEST = 'mygames/GAMES_LIVE_REQUEST';
export const GAMES_LIVE_FAILURE = 'mygames/GAMES_LIVE_FAILURE';
export const GAMES_LIVE_RECEIVE = 'mygames/GAMES_LIVE_RECEIVE';

export const GAMES_ALL_REQUEST = 'mygames/GAMES_ALL_REQUEST';
export const GAMES_ALL_FAILURE = 'mygames/GAMES_ALL_FAILURE';
export const GAMES_ALL_RECEIVE = 'mygames/GAMES_ALL_RECEIVE';

export const SET_MYGAMES_VISIBILITY_FILTER = 'mygames/SET_MYGAMES_VISIBILITY_FILTER';
