export const ADD_PLAYER = 'myteam/ADD_PLAYER';
export const LOAD_PLAYERS = 'myteam/LOAD_PLAYERS';
export const REMOVE_PLAYER = 'myteam/REMOVE_PLAYER';
export const SWAP_PLAYERS = 'myteam/SWAP_PLAYERS';
export const CLEAR = 'myteam/CLEAR';
export const RESET_FILTERS = 'myteam/RESET_FILTERS';
export const APPLY_SORT = 'myteam/APPLY_SORT';
export const FILTER_BY_POSITION = 'myteam/FILTER_BY_POSITION';
export const FILTER_BY_NAME = 'myteam/FILTER_BY_NAME';
export const FILTER_BY_TEAMS = 'myteam/FILTER_BY_TEAMS';
export const LOAD_MORE_ELEMENTS_INTO_INFINITE_PLAYERS_GRID = 'myteam/LOAD_MORE_ELEMENTS_INTO_INFINITE_PLAYERS_GRID';
export const SAVE_MY_TEAM = 'myteam/SAVE_MY_TEAM';
export const UPDATE_SELECTED_PLAYER_INDEX = 'myteam/UPDATE_SELECTED_PLAYER_INDEX';


export const PLAYER_STATS_REQUEST = 'myteam/PLAYER_STATS_REQUEST';
export const PLAYER_STATS_FAILURE = 'myteam/PLAYER_STATS_FAILURE';
export const PLAYER_STATS_RECEIVE = 'myteam/PLAYER_STATS_RECEIVE';

export const COMPARE_PLAYER_STATS_REQUEST = 'myteam/COMPARE_PLAYER_STATS_REQUEST';
export const COMPARE_PLAYER_STATS_FAILURE = 'myteam/COMPARE_PLAYER_STATS_FAILURE';
export const COMPARE_PLAYER_STATS_RECEIVE = 'myteam/COMPARE_PLAYER_STATS_RECEIVE';
